bar:
  location: bottom
  height: 32
  background: 1a1b26dd
  
  left:
    - script:
        path: /bin/sh
        args:
          - -c
          - |
            while true; do
              temp=$(awk '{printf "%.0f", $1/1000}' /sys/class/hwmon/hwmon5/temp1_input)
              echo "temp|string|${temp}Â°C"
              echo ""
              sleep 5
            done
        content:
          string:
            text: " {temp}"
            foreground: c0caf5ff
    
    - mem:
        poll-interval: 5000
        content:
          string:
            text: "  {percent_used}%"
            foreground: c0caf5ff

  center:
    - cpu:
        poll-interval: 1000
        content:
          string:
            text: "  {cpu}%"
            foreground: c0caf5ff

  right:
    - alsa:
        card: default
        mixer: Master
        content:
          map:
            conditions:
              ~muted:
                string:
                  text: "  {percent}%"
                  foreground: c0caf5ff
              muted:
                string:
                  text: "  {percent}%"
                  foreground: 7aa2f7ff
    
    - clock:
        time-format: "%H:%M | %e %B"
        content:
          string:
            text: " {time}"
            foreground: c0caf5ff
    
    - battery:
        name: BAT1
        poll-interval: 60000
        content:
          map:
            conditions:
              state == charging:
                string:
                  text: "  {capacity}% Charging"
                  foreground: 9ece6aff
              state == discharging && capacity >= 50:
                string:
                  text: "  {capacity}% Discharging"
                  foreground: c0caf5ff
              state == discharging && capacity >= 20:
                string:
                  text: "  {capacity}% Discharging"
                  foreground: e0af68ff
              state == discharging:
                string:
                  text: "  {capacity}% Discharging"
                  foreground: f7768eff
              state == full:
                string:
                  text: "  {capacity}% Full"
                  foreground: 9ece6aff
              state == "not charging":
                string:
                  text: "  {capacity}% Idle"
                  foreground: 7aa2f7ff
