bar:
  location: bottom
  height: 36
  background: 11121dfa
  
  left:
    - script:
        path: /bin/sh
        args:
          - -c
          - |
            while true; do
              temp=$(awk '{printf "%.0f", $1/1000}' /sys/class/hwmon/hwmon5/temp1_input)
              echo "temp|string|${temp}Â°C"
              echo ""
              sleep 5
            done
        content:
          string:
            text: "  {temp}"
            foreground: 7dcfffff
            font: JetBrainsMono Nerd Font:size=11
          
    - mem:
        poll-interval: 5000
        content:
          string:
            text: "    {percent_used}%"
            foreground: c099ffff
            font: JetBrainsMono Nerd Font:size=11
    
    - cpu:
        poll-interval: 1000
        content:
          string:
            text: "    {cpu}%"
            foreground: c3e88dff
            font: JetBrainsMono Nerd Font:size=11
  
  center:
    - clock:
        time-format: "%H:%M"
        date-format: "%A, %d %B"
        content:
          string:
            text: "{time}  {date}"
            foreground: 82aaffff
            font: JetBrainsMono Nerd Font:size=11:weight=semibold
  
  right:
    - alsa:
        card: default
        mixer: Master
        content:
          map:
            conditions:
              ~muted:
                string:
                  text: "  {percent}%"
                  foreground: ffc777ff
                  font: JetBrainsMono Nerd Font:size=11
              muted:
                string:
                  text: "  {percent}%"
                  foreground: 697098ff
                  font: JetBrainsMono Nerd Font:size=11
    
    - battery:
        name: BAT1
        poll-interval: 60000
        content:
          string:
            text: "    {capacity}%"
            foreground: ff757fff
            font: JetBrainsMono Nerd Font:size=11
